<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Product>Enbrea Edoosys.DB</Product>
    <Description>Reader class for the edoo.sys RLP database</Description>
    <Authors>STÜBER SYSTEMS GmbH</Authors>
    <Company>STÜBER SYSTEMS GmbH</Company>
    <Copyright>© 2026 STÜBER SYSTEMS GmbH</Copyright>
    <Version>0.6.0</Version>
    <LangVersion>latest</LangVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>enbrea;edoosys;rlp;database;reader;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/enbrea/enbrea.edoosys.db</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
